// Generated by CoffeeScript 2.7.0
// 直接将 pipeLib 声明为主力组装函数
var pipeLib;

pipeLib = function(fn, prevTask = (function() {}), layerIndex = 1) {
  if (fn === 0) {
    return function(...runArgs) {
      return prevTask(...runArgs);
    };
  }
  if ((fn != null ? fn.endSign : void 0) === 1) {
    return fn(this, prevTask, layerIndex);
  }
  return function(...buildArgs) {
    var currentTask;
    currentTask = function(...runArgs) {
      var err, fnName, ref;
      ref = function() {
        return prevTask(...runArgs);
      };
      try {
        // 核心：透传三元组参数
        return fn(ref, buildArgs, runArgs);
      } catch (error) {
        err = error;
        if (err.pipeLayer == null) {
          fnName = fn.name || "Anonymous Function";
          err.pipeLayer = layerIndex;
          err.message = `[Pipeline Layer ${layerIndex} <${fnName}> Error] -> ` + err.message;
        }
        throw err;
      }
    };
    return {
      // 递归调用 pipeLib 本身
      to: function(nextFn) {
        return pipeLib(nextFn, currentTask, layerIndex + 1);
      },
      _: function(nextFn) {
        return pipeLib(nextFn, currentTask, layerIndex + 1);
      }
    };
  };
};

pipeLib.use = (ref, buildArgs, runArgs) => {
  var subPipelineExecutor, upperData;
  [subPipelineExecutor] = buildArgs;
  upperData = ref();
  if ((upperData != null) && typeof upperData.then === 'function') {
    return upperData.then((resolvedData) => {
      return subPipelineExecutor(resolvedData);
    });
  }
  return subPipelineExecutor(upperData);
};

pipeLib.print = (ref, buildArgs, runArgs) => {
  var prefix, result;
  result = ref(); // 严格单次决议
  prefix = buildArgs[0];
  if ((result != null) && typeof result.then === 'function') {
    return result.then((resolvedData) => {
      if (prefix) {
        console.log(prefix, resolvedData);
      } else {
        console.log(resolvedData);
      }
      return resolvedData;
    });
  }
  if (prefix) {
    console.log(prefix, result);
  } else {
    console.log(result);
  }
  return result;
};

pipeLib.end = (ctx, prevTask, layerIndex) => {
  return (...runArgs) => {
    return prevTask(...runArgs);
  };
};

pipeLib.end.endSign = 1;

// 辅助算子：用于直接注入一个静态数据作为管道源头
pipeLib.value = (ref, buildArgs, runArgs) => {
  return buildArgs[0];
};

module.exports = pipeLib;
