// Generated by CoffeeScript 2.6.1
var pipeLib;

pipeLib = function() {};

pipeLib.start = function(fn) {
  if (fn.endSign) {
    return fn.call(this);
  } else {
    return (function(...args) {
      return pipeLib.start.bind(fn.call(this, ...args));
    }).bind(this);
  }
};

pipeLib.开始 = pipeLib.start;

pipeLib.print = function() {
  console.log(this);
  return this;
};

pipeLib.输出 = pipeLib.print;

pipeLib.end = function() {
  return this;
};

pipeLib.end.endSign = 1;

pipeLib.结束 = pipeLib.end;

module.exports = pipeLib;

/*
newArr = -> []
push = (args...)->
  this.push args...
  @

console.log  pipeLib.start(newArr)()(push)(3)(push)(4)(pipeLib.end)
*/
